### ISSUE TITLE
not working, need help

### ISSUE THREAD

**Issue by Geniusssmit** [shiiion/steinsgate_textractor#1]
it's not working for me. Clipboard is empty. Only thing I can see is ![image](https://user-images.githubusercontent.com/24941285/72460914-cffdb700-37de-11ea-99b3-a298961d6d23.png)

**Comment by Geniusssmit** [comment]
that's my steins gate folder 
![image](https://user-images.githubusercontent.com/24941285/72461236-9d07f300-37df-11ea-8867-fef9078cc4e1.png)

**Comment by shiiion** [comment]
~~If you compiled debug, the signature scanner is probably taking a while. Try compiling release and running it.~~ I realize you were sent a pre-built (presumably release) copy, see below comment.

**Comment by shiiion** [comment]
It's very hard to debug this without a version of your game executable, so we should move this somewhere else.
Contact me through e-mail if you don't mind, and we'll sort it out there: mayansymbol@gmail.com

**Comment by Geniusssmit** [comment]
Sure. btw it's Steam Japanese version

**Comment by shiiion** [comment]
Update: Currently running but copying out text incorrectly, issues were:

1. Searching for the process by window name can have false positives. In this case, a folder named Steins;Gate being opened will have two FindWindowA results for "Steins;Gate". Solution is to search for processes named Game.exe and query the user if they want to attach to the process discovered, or which process to attach to if >= 2 results.
2. Newer Steam version had a different string in its .rdata section for Steins;Gate. Tested version had the result "Steins;Gate\", whereas his version had "STEINS;GATE\". Solution is to stop searching based on strings in .rdata, as they may be subject to change between versions. Searching for byte patterns in .text unique to each game to do game detection.

**Comment by shiiion** [comment]
The given version has a different font compared to the version this was built on. Looking for solution

**Comment by shiiion** [comment]
Fixed with commit a6dcb3f83ee0e4d8c78e485cc1c47423c7de0375, thanks to @Geniusssmit for slogging through the OCR-ed font page. Credit will be added in readme.
