### ISSUE TITLE
Extracted text uses wrong characters

### ISSUE THREAD

**Issue by Kuratius** [shiiion/steinsgate_textractor#10]
![grafik](https://user-images.githubusercontent.com/47481645/127757001-9684b8f9-870b-4f00-8c95-1af3aa7956a8.png)

![grafik](https://user-images.githubusercontent.com/47481645/127757015-50a3d93c-4a5e-44e5-a623-8c232f455c60.png)
![Textractor_BRpUMSDuKX](https://user-images.githubusercontent.com/47481645/127757019-5df74dea-fa0f-48ee-b463-6210708740cf.png)

**Comment by cyphar** [comment]
If you're using the steam version, rename `mages_charset_steam.bin` to `mages_charset.bin` (deleting or moving the old one).

**Comment by Kuratius** [comment]
That seems to have fixed it. Thank you. It's a really weird issue. Instead of not working it makes it look like it's based on some sort of failed OCR.
