### ISSUE TITLE
LBP/Darling fixes

### ISSUE THREAD

**Issue by AuroraWright** [shiiion/steinsgate_textractor#17]
I've been working on fixing issues with LBP and Darling these past few days, they should both work now BUT pay attention to kanjis for both games since I had to make a charset for each via OCR and there are potential errors (I'd actually really appreciate if you reported kanji errors here so they could be fixed! Here's a zip file with a patched .exe which includes https://github.com/shiiion/steinsgate_textractor/pull/16 and includes the charsets I threw together (EDIT: updated fixing a few kanjis by comparing the outputs of two OCR models) (EDIT2: proofread charsets!)
[sg_textractor.zip](https://github.com/shiiion/steinsgate_textractor/files/9193621/sg_textractor.zip)

**Comment by Feldrius** [comment]
THANK YOU so much! I'll be sure to report any issues I find.

**Comment by AuroraWright** [comment]
@SofiaScarlet has proofread the charsets, updated the zip above and the PR
