### ISSUE TITLE
Chaos;Head NoaH support

### ISSUE THREAD

**Issue by natto1784** [shiiion/steinsgate_textractor#18]
Does this work with [Chaos;Head NoaH](https://store.steampowered.com/app/1961950/CHAOSHEAD_NOAH/)? If not, how about expanding? I can help if required.

**Comment by AuroraWright** [comment]
No this only works on Steins;Gate games (except for Elite), it probably could support other stuff but it would require reverse engineering for each game + work to make a charset for each game
