### ISSUE TITLE
Support for spin-off?

### ISSUE THREAD

**Issue by scese250** [shiiion/steinsgate_textractor#2]
Linear Bounded Phenogram and My Darlings Embrace if it's not much work... :)

**Comment by shiiion** [comment]
This shouldn't be very hard, these games seem very similar in structure.

**Comment by shiiion** [comment]
Funnily enough (probably due to the sigscan), this is already functional, the phone needs some fixing though.

**Comment by shiiion** [comment]
My Darlings Embrace supported as of c15ce770ec839df9cf82bb300b9126c57b829636

**Comment by shiiion** [comment]
Linear Bounded Phenogram is also working. I'll consider this closed for the time being.
