### ISSUE TITLE
SG My Darling's Embrace Support

### ISSUE THREAD

**Issue by zHElEARN** [shiiion/steinsgate_textractor#4]
SG My Darling's Embrace Support

**Comment by shiiion** [comment]
I believe I tested it and it is already supported (similar enough to original s;g). Please confirm.

**Comment by zHElEARN** [comment]
```
活动代码页: 936
Looking for Steins;Gate or STEINS;GATE 0 process (Game.exe)
WARNING! This will write memory to the target process, so careful what you attach to!
Game.exe found with PID=9472
Attach to this process? (y/n) : y
Loading signatures
Failed to load signatures
```

what should I do

**Comment by Zezoo333** [comment]
sadly I have the same problem.
They really made it hard with their engine unfortunately.

**Comment by Feldrius** [comment]
Same problem. Linear Bounded Phenogram fortunately works, but My Darling's Embrace does not. It's a real pity, as it appears that nobody else has even tried to make something like this for MDE and, honestly, relying on OCR is not a very good option. The standard textractor that most people use does not support the Mages. engine and it doesn't appear that it ever will.

@shiiion, should you read this, I beg you to consider fixing this issue. This textractor has been an absolute godsend to the japanese immersion learning community, and it's a shame that it doesn't work with S;G:MDE. Me and many people would be **eternally** grateful if you managed to make it work. Please, consider it!

edit: Actually, it doesn't really work on Linear Bounded Phenogram either as it displays the wrong characters.

**Comment by AuroraWright** [comment]
See here: https://github.com/shiiion/steinsgate_textractor/issues/17
