### ISSUE TITLE
Steins; Gate 0: Failed to load signatures

### ISSUE THREAD

**Issue by ThisCakeIsALie** [shiiion/steinsgate_textractor#5]
# The problem
When trying to attach to Steins; Gate 0 it fails while loading the signatures.
![image](https://user-images.githubusercontent.com/37264026/87245642-5837de80-c447-11ea-9890-2d4f8ddb4eb2.png)

# The context
I am using the latest Steam release version of Steins; Gate 0 on Windows 10.

# A hint
After digging through the code a bit it seems like ```initialize_sg0_sigs```  doesn't find all the correct values as ```results[3]```, ```results[11]``` and ```results[12]``` all appear to be ```0```.

**Comment by shiiion** [comment]
It seems that the game was recompiled and some compiler optimizations ended up switching instructions around. The sigs have been adjusted, compile the updated version ff51443 and test it.

**Comment by ThisCakeIsALie** [comment]
Works like a charm. Thanks for the fast response :)
